version: '3.7'

services:

  accomodation-list-fe:
    container_name: accomodation-list-fe
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8081:8080'