version: '3.7'

services:

  map-my-plan-fe:
    container_name: map-my-plan-fe
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8081:8080'